# Generated by Django 4.0.6 on 2022-07-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('izmerenie', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('al', 'alive'), ('dd', 'dead'), ('un', 'unknown')], max_length=250)),
                ('desc', models.TextField()),
                ('race', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('ml', 'male'), ('fl', 'female'), ('gl', 'genderless'), ('un', 'unknown')], max_length=250)),
                ('birth_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_birth', to='characters.location')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.location')),
            ],
        ),
    ]
