# Generated by Django 4.0.6 on 2022-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Characters_rick_morti'),
        ),
        migrations.AlterField(
            model_name='location',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='location_rick_morti'),
        ),
    ]
