# Generated by Django 4.0.6 on 2022-07-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_img_alter_location_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('ml', 'male'), ('fm', 'female'), ('gl', 'genderless'), ('un', 'unknown')], max_length=250),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('numb_episode', models.IntegerField(verbose_name='серия:')),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='episode_rick_morty')),
                ('characters', models.ManyToManyField(blank=True, null=True, to='characters.character')),
            ],
        ),
    ]
